// Code generated by scripts/generate_contracts.py. DO NOT EDIT.
// Source Contract: cmapss_engine_telemetry v1.0.0

package database

// FlightRecord — автосгенерированный Data Contract L2.
// Отражает одну строку физики из транзакционной базы SQLite.
type FlightRecord struct {
	Id int32 `json:"id" db:"id"` // Суррогатный ключ для идемпотентности (Защита от дублей в Iceberg)
	Status string `json:"status" db:"status"` // Статус обработки полетного цикла (PENDING/COMPLETED/FAILED)
	FlightStartTime string `json:"flight_start_time" db:"flight_start_time"` // ISO8601 временная метка начала симуляции полета
	TargetDurationSec int32 `json:"target_duration_sec" db:"target_duration_sec"` // Ожидаемая длительность полета в секундах (Target length)
	UnitNumber int32 `json:"unit_number" db:"unit_number"` // Уникальный идентификатор борта (турбины)
	TimeCycles int32 `json:"time_cycles" db:"time_cycles"` // Текущее время жизни двигателя (в полетных циклах) [cycles]
	OpSetting1 float64 `json:"op_setting_1" db:"op_setting_1"` // Операционная настройка 1: Высота полета (Altitude) [ft]
	OpSetting2 float64 `json:"op_setting_2" db:"op_setting_2"` // Операционная настройка 2: Число Маха (Скорость) [Mach]
	OpSetting3 float64 `json:"op_setting_3" db:"op_setting_3"` // Операционная настройка 3: Угол положения дросселя (Throttle Resolver Angle) [TRA]
	T2 float64 `json:"T2" db:"T2"` // Полная температура на входе вентилятора [°R]
	T24 float64 `json:"T24" db:"T24"` // Полная температура на выходе LPC (компрессора низкого давления) [°R]
	T30 float64 `json:"T30" db:"T30"` // Полная температура на выходе HPC (компрессора высокого давления) [°R]
	T50 float64 `json:"T50" db:"T50"` // Полная температура на выходе LPT (турбины низкого давления). Главный маркер EGT Margin. [°R]
	P2 float64 `json:"P2" db:"P2"` // Давление на входе вентилятора [psia]
	P15 float64 `json:"P15" db:"P15"` // Полное давление в байпасном канале [psia]
	P30 float64 `json:"P30" db:"P30"` // Полное давление на выходе HPC [psia]
	Nf float64 `json:"Nf" db:"Nf"` // Физическая скорость вращения вентилятора (Ground Truth Anchor) [rpm]
	Nc float64 `json:"Nc" db:"Nc"` // Физическая скорость вращения ядра (ротора) [rpm]
	Epr float64 `json:"epr" db:"epr"` // Степень повышения давления двигателя (P50/P2) [ratio]
	Ps30 float64 `json:"Ps30" db:"Ps30"` // Статическое давление на выходе HPC [psia]
	Phi float64 `json:"phi" db:"phi"` // Отношение расхода топлива к статическому давлению Ps30 [pps/psi]
	Nrf float64 `json:"NRf" db:"NRf"` // Скорректированная скорость вращения вентилятора [rpm]
	Nrc float64 `json:"NRc" db:"NRc"` // Скорректированная скорость вращения ядра [rpm]
	Bpr float64 `json:"BPR" db:"BPR"` // Байпасное отношение (Bypass Ratio) [ratio]
	Farb float64 `json:"farB" db:"farB"` // Отношение топливовоздушной смеси горелки [ratio]
	Htbleed float64 `json:"htBleed" db:"htBleed"` // Энтальпия отбираемого воздуха [btu/lbm]
	NfDmd float64 `json:"Nf_dmd" db:"Nf_dmd"` // Требуемая скорость вентилятора (Запрос тяги) [rpm]
	PcnfrDmd float64 `json:"PCNfR_dmd" db:"PCNfR_dmd"` // Требуемая скорректированная скорость вентилятора [rpm]
	W31 float64 `json:"W31" db:"W31"` // Расход охлаждающей жидкости HPT [lbm/s]
	W32 float64 `json:"W32" db:"W32"` // Расход охлаждающей жидкости LPT [lbm/s]
}
