"""
Скрипт кодогенерации (Data Contract Translator) для C-MAPSS Симулятора.
Превращает единый источник истины (YAML) в исполняемые артефакты:
1. SQL DDL для инициализации SQLite (миграции).
2. Go Structs для использования в Ingestion Gateway и Spark/Edge контурах.

AI-Ready Standard: 
Строгая типизация, исчерпывающие докстринги, защита от перезаписи ручного кода.
"""

import sys
import yaml
import logging
from datetime import datetime, timezone
from pathlib import Path

# Настройка Enterprise-логирования
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)

# Маппинг абстрактных типов из Data Contract в специфичные языки
# Используем int32 для Go, так как unit_number и cycles не превысят лимиты
SQL_TYPE_MAP = {"integer": "INTEGER", "float": "REAL", "string": "TEXT"}
GO_TYPE_MAP = {"integer": "int32", "float": "float64", "string": "string"}


def generate_sql_ddl(contract: dict) -> str:
    """
    Генерирует SQL-скрипт миграции из YAML-контракта.
    
    Args:
        contract (dict): Распарсенный YAML словарь.
        
    Returns:
        str: Готовый SQL DDL скрипт с комментариями и индексами.
    """
    table_name = "flights"
    generation_time = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    
    lines = [
        f"-- ==========================================================",
        f"-- АВТОГЕНЕРАЦИЯ ИЗ {contract.get('name', 'UNKNOWN')} v{contract.get('version', '0.0.0')}",
        f"-- ДАТА ГЕНЕРАЦИИ: {generation_time}",
        f"-- ВЛАДЕЛЕЦ: {contract.get('owner', 'Data_Platform_Team')}",
        f"-- НЕ РЕДАКТИРОВАТЬ ВРУЧНУЮ! ВСЕ ИЗМЕНЕНИЯ ВНОСИТЬ В YAML.",
        f"-- ==========================================================\n",
        f"DROP TABLE IF EXISTS {table_name};\n",
        f"CREATE TABLE {table_name} ("
    ]
    
    columns = []
    
    # 1. Генерация системных колонок (Метаданные пайплайна)
    for col in contract["schema"].get("system_columns", []):
        col_def = f"    {col['name']} {SQL_TYPE_MAP[col['type']]}"
        if col.get("primary_key"):
            col_def += " PRIMARY KEY"
        if col.get("autoincrement"):
            col_def += " AUTOINCREMENT"
        if "default" in col:
            col_def += f" DEFAULT {col['default']}"
        columns.append(col_def)
        
    # 2. Генерация доменных колонок (Физика турбины)
    for col in contract["schema"].get("domain_columns", []):
        col_def = f"    {col['name']} {SQL_TYPE_MAP[col['type']]}"
        if col.get("required"):
            col_def += " NOT NULL"
        columns.append(col_def)
        
    lines.append(",\n".join(columns))
    lines.append(");\n")
    
    # 3. Генерация индексов для быстрой работы CDC и Spark
    for idx in contract.get("indexes", []):
        cols = ", ".join(idx["columns"])
        lines.append(f"CREATE INDEX IF NOT EXISTS {idx['name']} ON {table_name}({cols});")
        
    return "\n".join(lines)


def generate_go_struct(contract: dict) -> str:
    """
    Генерирует структуру данных на языке Go (Data Object).
    
    Args:
        contract (dict): Распарсенный YAML словарь.
        
    Returns:
        str: Готовый код на Go с тегами json и db для ORM/Сериализации.
    """
    # Стандартный комментарий для Go-линтеров, отключающий проверки ручного кода
    lines = [
        "// Code generated by scripts/generate_contracts.py. DO NOT EDIT.",
        f"// Source Contract: {contract.get('name', 'UNKNOWN')} v{contract.get('version', '0.0.0')}",
        "",
        "package database\n",
        "// FlightRecord — автосгенерированный Data Contract L2.",
        "// Отражает одну строку физики из транзакционной базы SQLite.",
        "type FlightRecord struct {"
    ]
    
    all_cols = contract["schema"].get("system_columns", []) + contract["schema"].get("domain_columns", [])
    
    for col in all_cols:
        # Капитализация для экспорта поля в Go (unit_number -> UnitNumber)
        go_name = "".join(word.capitalize() for word in col['name'].split('_'))
        go_type = GO_TYPE_MAP[col['type']]
        
        # Добавляем JSON и DB теги для легкой интеграции с Kafka и SQLite ORM
        json_tag = f'`json:"{col["name"]}" db:"{col["name"]}"`'
        
        # Извлекаем описание и единицы измерения для AI-Ready комментариев
        description = col.get("description", "")
        unit = f" [{col['unit']}]" if "unit" in col else ""
        comment = f"// {description}{unit}".strip()
        
        # Формируем строку структуры
        lines.append(f"\t{go_name} {go_type} {json_tag} {comment}")
        
    lines.append("}\n")
    return "\n".join(lines)


def main():
    """Точка входа. Управляет путями, читает YAML и пишет файлы."""
    project_root = Path(__file__).resolve().parent.parent
    
    contract_path = project_root / "schemas" / "engine_telemetry_contract.yaml"
    sql_out_path = project_root / "schemas" / "migrations" / "V001_initial_schema.sql"
    # ИСПРАВЛЕНИЕ: Выделяем автосгенерированный код в отдельный файл!
    go_out_path = project_root / "internal" / "database" / "schema_generated.go"
    
    logging.info(f"Старт кодогенерации из источника: {contract_path}")
    
    if not contract_path.exists():
        logging.error(f"CRITICAL: YAML контракт не найден по пути {contract_path}")
        sys.exit(1)
        
    try:
        with open(contract_path, "r", encoding="utf-8") as f:
            contract_data = yaml.safe_load(f)
    except yaml.YAMLError as exc:
        logging.error(f"CRITICAL: Ошибка парсинга YAML контракта: {exc}")
        sys.exit(1)
        
    # 1. Генерация SQL (Data Definition Language)
    try:
        sql_out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(sql_out_path, "w", encoding="utf-8") as f:
            f.write(generate_sql_ddl(contract_data))
        logging.info(f"SUCCESS: SQL миграция сгенерирована -> {sql_out_path.name}")
    except Exception as e:
        logging.error(f"Ошибка при записи SQL: {e}")
        
    # 2. Генерация Go Struct (Data Transfer Object)
    try:
        go_out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(go_out_path, "w", encoding="utf-8") as f:
            f.write(generate_go_struct(contract_data))
        logging.info(f"SUCCESS: Go структура сгенерирована -> {go_out_path.name}")
    except Exception as e:
        logging.error(f"Ошибка при записи Go структуры: {e}")
        
    logging.info("Генерация контрактов завершена. Завод готов к работе.")


if __name__ == "__main__":
    main()